# Generated by Django 2.2 on 2019-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='choice_field',
            field=models.CharField(choices=[('1', 'Question about applying'), ('2', 'Want to publish'), ('3', 'Other')], default='none', max_length=25),
        ),
    ]
