# Generated by Django 2.2 on 2019-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_comment_choice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moder',
            field=models.BooleanField(default=True, verbose_name='Moderation'),
        ),
    ]
