# Generated by Django 2.2 on 2019-04-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_auto_20190422_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
